# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee5745a3068e8a2181e621248b0a732f41f5aa26d3650e6501e89e11232973ca08825a2264108d9e28d9ff9d92b65583db1e0a18aaae953dd20e3b2e5957a7b7

test:
  secret_key_base: dc57bfa9b1160afc7dd6321aeb95e1d39894ea41ce79fe8d97546c32c02ff361cabfced30164e50687466a29e9b9779baee575d6b9c1145a2557b13666d29a0b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
